export enum EntityType {
  DETECTION = 'DETECTION',
  CVX = 'CVX',
  ADF = 'ADF',
  CONFIGURATION = 'CONFIGURATION',
  TEMPLATE = 'TEMPLATE',
  SECTION = 'SECTION',
  JOB = 'JOB',
  FACILITY = 'FACILITY',
  USER = 'USER',
  REPORT = 'REPORT',
}
